import 'package:flutter/material.dart';
import 'package:pinput/pinput.dart';
import '../../services/twilio_service.dart';
import '../../core/localization.dart';
import '../dashboard/home_screen.dart';

class PhoneSignInScreen extends StatefulWidget {
  const PhoneSignInScreen({super.key});

  @override
  State<PhoneSignInScreen> createState() => _PhoneSignInScreenState();
}

class _PhoneSignInScreenState extends State<PhoneSignInScreen> {
  final TextEditingController _phoneController = TextEditingController();
  final TextEditingController _otpController = TextEditingController();
  
  bool _isLoading = false;
  bool _codeSent = false;
  String _sentOTP = ''; // Generated by Twilio locally for demo

  void _sendTwilioOTP() async {
    final phone = _phoneController.text.trim();
    if (phone.isEmpty) return;

    // Localized prefix for India +91 as requested
    final fullNumber = '+91$phone';

    setState(() => _isLoading = true);

    try {
      // Direct Twilio REST Call
      final otp = await TwilioService.sendOTP(fullNumber);
      
      if (otp != null) {
        setState(() {
          _sentOTP = otp;
          _codeSent = true;
          _isLoading = false;
        });
        
        // ── PRO FEATURE: Simulated "Auto-Verify" for Demo ──
        // In a real app with 'sms_autofill', this would trigger when the SMS arrives.
        // For the hackathon demo, let's simulate the "Automated" feel!
        Future.delayed(const Duration(seconds: 4), () {
          if (mounted && _codeSent) {
             _otpController.text = _sentOTP;
             _verifyOTP(); // Automatically trigger verification 🚀
          }
        });
      } else {
        setState(() => _isLoading = false);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Failed to send SMS. Ensure your number is verified in Twilio.')),
        );
      }
    } catch (e) {
      setState(() => _isLoading = false);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Twilio Error: $e')),
      );
    }
  }

  void _verifyOTP() async {
    final code = _otpController.text.trim();
    if (code != _sentOTP) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Incorrect code. Please check your SMS.')),
        );
        return;
    }

    setState(() => _isLoading = true);

    // Automation complete! Success.
    await Future.delayed(const Duration(milliseconds: 800));
    
    if (mounted) {
      Navigator.pushAndRemoveUntil(
        context,
        MaterialPageRoute(builder: (_) => const HomeScreen()),
        (route) => false,
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final loc = AppLocalizations.of(context);
    final theme = Theme.of(context);

    // High-end PIN Input styling
    final defaultPinTheme = PinTheme(
      width: 56,
      height: 64,
      textStyle: const TextStyle(fontSize: 28, color: Color.fromRGBO(30, 60, 87, 1), fontWeight: FontWeight.w600),
      decoration: BoxDecoration(
        border: Border.all(color: Colors.green.shade200, width: 2),
        borderRadius: BorderRadius.circular(12),
      ),
    );

    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text(loc.get('continue_with_phone_otp')),
        backgroundColor: Colors.white,
        foregroundColor: Colors.green.shade900,
        elevation: 0,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(28.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const SizedBox(height: 20),
              Text(
                _codeSent ? loc.get('enter_otp') : loc.get('enter_phone'),
                style: theme.textTheme.headlineMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                  color: Colors.green.shade900,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                _codeSent 
                  ? '${loc.get('otp_sent_to')} +91 ${_phoneController.text}'
                  : loc.get('otp_helper'),
                style: const TextStyle(fontSize: 16, color: Colors.grey),
              ),
              const SizedBox(height: 48),
              
              if (!_codeSent)
                // Phone Input
                TextField(
                  controller: _phoneController,
                  keyboardType: TextInputType.phone,
                  autofocus: true,
                  style: const TextStyle(fontSize: 28, fontWeight: FontWeight.bold, letterSpacing: 2),
                  decoration: InputDecoration(
                    prefixText: '+91 ',
                    labelText: loc.get('phone_number'),
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                    contentPadding: const EdgeInsets.symmetric(vertical: 20, horizontal: 16),
                  ),
                )
              else
                // ── PRO UI: Pinput (Automated Look) ──
                Center(
                  child: Pinput(
                    length: 6,
                    controller: _otpController,
                    defaultPinTheme: defaultPinTheme,
                    focusedPinTheme: defaultPinTheme.copyDecorationWith(
                      border: Border.all(color: Colors.green.shade600, width: 3),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    submittedPinTheme: defaultPinTheme.copyWith(
                      decoration: defaultPinTheme.decoration?.copyWith(
                        color: Colors.green.shade50,
                      ),
                    ),
                    onCompleted: (pin) => _verifyOTP(),
                  ),
                ),

              const SizedBox(height: 48),
              
              if (_isLoading)
                Column(
                  children: [
                    const CircularProgressIndicator(),
                    const SizedBox(height: 16),
                    Text(_codeSent ? "AI Verifying OTP..." : "Sending Twilio SMS...", 
                        style: TextStyle(color: Colors.green.shade800, fontWeight: FontWeight.bold)),
                  ],
                )
              else
                ElevatedButton(
                  onPressed: _codeSent ? _verifyOTP : _sendTwilioOTP,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.green.shade700,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 18),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
                    elevation: 4,
                  ),
                  child: Text(
                    _codeSent ? loc.get('verify_otp') : loc.get('send_otp'),
                    style: const TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
                  ),
                ),
              
              if (_codeSent) ...[
                const SizedBox(height: 24),
                TextButton(
                  onPressed: () => setState(() => _codeSent = false),
                  child: const Text('Change Phone Number', 
                      style: TextStyle(fontSize: 16, decoration: TextDecoration.underline)),
                ),
                const SizedBox(height: 40),
                const Opacity(
                  opacity: 0.6,
                  child: Text(
                    "Powered by Twilio Automate ⚡\n(Live Demo Mode Active 🪄)",
                    textAlign: TextAlign.center,
                    style: TextStyle(fontStyle: FontStyle.italic, fontWeight: FontWeight.bold),
                  ),
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }
}
