import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? AppLocalizations(const Locale('en'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'app_name': 'Smart Kirana AI',
      'select_language': 'Select Language',
      'english': 'English',
      'telugu': 'తెలుగు (Telugu)',
      'hindi': 'हिंदी (Hindi)',
      'next': 'Next',
      'profile': 'Profile',
      'shop_name': 'Shop Name',
      'whatsapp_number': 'Your WhatsApp Number',
      'save_and_continue': 'Save & Continue',
      'dashboard': 'Smart Kirana',
      'inventory': 'Inventory',
      'analytics': 'Analytics',
      'tap_to_speak': 'Tap to speak sales / stock',
      'low_stock_alerts': 'Low Stock Alerts',
      'business_tips': 'AI Business Tips',
      'add_product': 'Add Product',
      'sell': 'Sell',
      'add_stock': 'Add Stock',
      'ai_pitch': 'Get AI Selling Pitch',
      'product_name': 'Product Name',
      'quantity': 'Quantity',
      'price': 'Price (₹)',
      'save': 'Save',
      'cancel': 'Cancel',
      'listening': 'Listening...',
      'sales': 'Sales',
      'today': 'Today',
      'send_reorder_list': 'Send Reorder List',
      'supplier_whatsapp': 'Supplier WhatsApp Number',
      'login_to_backup': 'Log in with Google to back up your data safely to the cloud',
      'continue_with_google': 'Continue with Google',
      'continue_with_phone_otp': 'Continue with Phone / OTP',
      'enter_phone': 'Enter Phone Number',
      'phone_number': 'Phone Number',
      'send_otp': 'Send SMS Code',
      'verify_otp': 'Verify & Start',
      'enter_otp': 'Enter 6-digit Code',
      'otp_sent_to': 'SMS code sent to',
      'invalid_otp': 'Invalid code. Try again.',
      'sync_disclaimer': 'Your data is safe in the cloud',
      'log_sale': 'Log Sale',
      'quantity_sold': 'Quantity Sold',
      'confirm_sale': 'Confirm Sale',
      'add_stock_title': 'Add Stock',
      'quantity_to_add': 'Quantity to Add',
      'current_stock': 'Current Stock',
      'stock_qty_label': 'Stock Quantity',
      'critical_stock_alert': '📦 CRITICAL STOCK ALERT!',
      'order_now': 'Order Now',
      'remind_me': 'Remind Me Later',
      'supplier_msg_template': 'Hello! I need an urgent delivery of {product}. My current stock is only {qty}. Please send soon. Thank you! - {shop}',
      'self_reminder_template': '📌 REMINDER: Buy more {product}. Only {qty} units left in the shop.',
      'bill_generator': '🧾 Bill Generator',
      'customer_whatsapp': 'Customer WhatsApp Number',
      'tap_product_to_add': 'Tap a product to add to bill:',
      'bill_helper_text': 'Bill will be sent directly to this number',
      'add_items_first': 'Add items to the bill first!',
      'send_bill_whatsapp': 'Send Bill on WhatsApp',
      'total': 'Total',
      'cash_in': '💰 Cash In',
      'units_sold_label': '📦 Units Sold',
      'store_superstar': '🏆 Store Superstar',
      'growth_trend': '📈 Growth Shape (Last 7 Days)',
      'all_performance': '🔥 All Sales Performance',
      'sold_count_template': 'Sold {count} times this week!',
      'thank_you_shopping': 'Thank you for shopping!',
      'voice_sold': 'Sold {qty} units of {product}.',
      'voice_added': 'Added {qty} units to {product}.',
      'voice_new_product': 'New product {product} added with {qty} units.',
      'voice_stock_status': 'You have {qty} units of {product} left in shop.',
      'voice_not_found': 'I could not find {product} in your inventory.',
      'voice_error': 'I am sorry, I could not understand that.',
      'stock_low_warning': '{product} is very low: Only {qty} left!',
      'reorder_reminder_time': 'Reorder Reminder Time',
    },
    'te': {
      'app_name': 'స్మార్ట్ కిరాణా AI',
      'select_language': 'భాషను ఎంచుకోండి',
      'english': 'English',
      'telugu': 'తెలుగు (Telugu)',
      'hindi': 'हिंदी (Hindi)',
      'next': 'తరువాత',
      'profile': 'ప్రొఫైల్',
      'shop_name': 'దుకాణం పేరు',
      'whatsapp_number': 'మీ వాట్సాప్ నంబర్',
      'save_and_continue': 'సేవ్ చేయండి',
      'dashboard': 'స్మార్ట్ కిరాణా',
      'inventory': 'వస్తువుల జాబితా',
      'analytics': 'విశ్లేషణలు',
      'tap_to_speak': 'మాట్లాడటానికి నొక్కండి',
      'low_stock_alerts': 'తక్కువ స్టాక్ హెచ్చరికలు',
      'business_tips': 'AI వ్యాపార చిట్కాలు',
      'add_product': 'వస్తువును జోడించండి',
      'sell': 'అమ్మండి',
      'add_stock': 'స్టాక్ కలపండి',
      'ai_pitch': 'AI సేల్స్ పిచ్ పొందుకోండి',
      'product_name': 'వస్తువు పేరు',
      'quantity': 'పరిమాణం',
      'price': 'ధర (₹)',
      'save': 'సేవ్',
      'cancel': 'రాద్దు చేయి',
      'listening': 'వింటున్నాను...',
      'sales': 'అమ్మకాలు',
      'today': 'ఈ రోజు',
      'send_reorder_list': 'కొత్త స్టాక్ కోసం మెసేజ్',
      'supplier_whatsapp': 'సప్లయర్ వాట్సాప్ నంబర్',
      'login_to_backup': 'డేటాను క్లౌడ్‌కి సురక్షితంగా బ్యాకప్ చేయడానికి Googleతో లాగిన్ అవ్వండి',
      'continue_with_google': 'Googleతో కొనసాగండి',
      'continue_with_phone_otp': 'ఫోన్ / OTP ద్వారా కొనసాగండి',
      'enter_phone': 'ఫోన్ నంబర్ నమోదు చేయండి',
      'phone_number': 'ఫోన్ నంబర్',
      'send_otp': 'కోడ్ పంపండి',
      'verify_otp': 'నిర్ధారించండి',
      'enter_otp': '6 అంకెల కోడ్ ఎంటర్ చేయండి',
      'otp_sent_to': 'కోడ్ పంపబడదు: ',
      'invalid_otp': 'తప్పు కోడ్. మళ్ళీ ప్రయత్నించండి.',
      'sync_disclaimer': 'మీ డేటా సురక్షితంగా ఉంటుంది',
      'log_sale': 'అమ్మకాన్ని నమోదు చేయండి',
      'quantity_sold': 'అమ్మిన పరిమాణం',
      'confirm_sale': 'అమ్మకాన్ని నిర్ధారించండి',
      'add_stock_title': 'స్టాక్ పెంచండి',
      'quantity_to_add': 'జోడించాల్సిన పరిమాణం',
      'current_stock': 'ప్రస్తుత స్టాక్',
      'stock_qty_label': 'స్టాక్ పరిమాణం',
      'critical_stock_alert': '📦 అత్యవసర స్టాక్ హెచ్చరిక!',
      'order_now': 'ఇప్పుడే ఆర్డర్ చేయండి',
      'remind_me': 'తరువాత గుర్తు చేయి',
      'supplier_msg_template': 'నమస్కారం! నాకు అత్యవసరంగా {product} కావాలి. ప్రస్తుతం నా వద్ద కేవలం {qty} మాత్రమే ఉన్నాయి. దయచేసి త్వరగా పంపండి. ధన్యవాదాలు! - {shop}',
      'self_reminder_template': '📌 రిమైండర్: {product} కొనాలి. కేవలం {qty} మాత్రమే మిగిలి ఉన్నాయి.',
      'bill_generator': '🧾 బిల్ జనరేటర్',
      'customer_whatsapp': 'కస్టమర్ వాట్సాప్ నంబర్',
      'tap_product_to_add': 'బిల్లులో చేర్చడానికి వస్తువును నొక్కండి:',
      'bill_helper_text': 'బిల్లు నేరుగా ఈ నంబర్‌కు పంపబడుతుంది',
      'add_items_first': 'ముందుగా బిల్లులో వస్తువులను చేర్చండి!',
      'send_bill_whatsapp': 'వాట్సాప్‌లో బిల్ పంపండి',
      'total': 'మొత్తం',
      'cash_in': '💰 నగదు',
      'units_sold_label': '📦 అమ్మిన యూనిట్లు',
      'store_superstar': '🏆 స్టోర్ సూపర్ స్టార్',
      'growth_trend': '📈 వృద్ధి తీరు (గత 7 రోజులు)',
      'all_performance': '🔥 అన్ని అమ్మకాల పనితీరు',
      'sold_count_template': 'ఈ వారం {count} సార్లు అమ్మారు!',
      'thank_you_shopping': 'మా వద్ద కొన్నందుకు ధన్యవాదాలు!',
      'voice_sold': '{product} {qty} యూనిట్లు అమ్మబడ్డాయి.',
      'voice_added': '{product} కి {qty} యూనిట్లు చేర్చబడ్డాయి.',
      'voice_new_product': 'కొత్త వస్తువు {product} {qty} యూనిట్లతో చేర్చబడింది.',
      'voice_stock_status': 'మీ వద్ద {product} {qty} యూనిట్లు మిగిలి ఉన్నాయి.',
      'voice_not_found': 'మీ ఇన్వెంటరీలో {product} కనిపించలేదు.',
      'voice_error': 'క్షమించండి, నాకు అది అర్థం కాలేదు.',
      'stock_low_warning': '{product} చాలా తక్కువగా ఉంది: కేవలం {qty} మాత్రమే మిగిలి ఉన్నాయి!',
      'reorder_reminder_time': 'రిమైండర్ సమయం',
    },
    'hi': {
      'app_name': 'स्मार्ट किराना AI',
      'select_language': 'भाषा चुनें',
      'english': 'English',
      'telugu': 'తెలుగు (Telugu)',
      'hindi': 'हिंदी (Hindi)',
      'next': 'आगे बढ़ें',
      'profile': 'प्रोफ़ाइल',
      'shop_name': 'दुकान का नाम',
      'whatsapp_number': 'आपका व्हाट्सएप नंबर',
      'save_and_continue': 'सेव करें',
      'dashboard': 'स्मार्ट किराना',
      'inventory': 'सामान की सूची',
      'analytics': 'विश्लेषण',
      'tap_to_speak': 'बोलने के लिए दबाएं',
      'low_stock_alerts': 'कम स्टॉक अलर्ट',
      'business_tips': 'AI बिजनेस टिप्स',
      'add_product': 'सामान जोड़ें',
      'sell': 'बेचें',
      'add_stock': 'स्टॉक जोड़ें',
      'ai_pitch': 'AI सेलिंग पिच प्राप्त करें',
      'product_name': 'सामान का नाम',
      'quantity': 'मात्रा',
      'price': 'कीमत (₹)',
      'save': 'सेव',
      'cancel': 'रद्द करें',
      'listening': 'सुन रहा हूँ...',
      'sales': 'बिक्री',
      'today': 'आज',
      'send_reorder_list': 'रीऑर्डर लिस्ट भेजें',
      'supplier_whatsapp': 'सप्लायर का व्हाट्सएप नंबर',
      'login_to_backup': 'अपने डेटा को क्लाउड पर सुरक्षित रूप से बैकअप करने के लिए Google के साथ लॉग इन करें',
      'continue_with_google': 'गूगल के साथ आगे बढ़ें',
      'continue_with_phone_otp': 'फ़ोन / OTP के साथ आगे बढ़ें',
      'enter_phone': 'फ़ोन नंबर दर्ज करें',
      'phone_number': 'फ़ोन नंबर',
      'send_otp': 'कोड भेजें',
      'verify_otp': 'पुष्टि करें',
      'enter_otp': '6 अंकों का कोड दर्ज करें',
      'otp_sent_to': 'कोड भेजा गया: ',
      'invalid_otp': 'गलत कोड. फिर से कोशिश करें.',
      'sync_disclaimer': 'आपका डेटा सुरक्षित है',
      'log_sale': 'बिक्री दर्ज करें',
      'quantity_sold': 'बेची गई मात्रा',
      'confirm_sale': 'बिक्री की पुष्टि करें',
      'add_stock_title': 'स्टॉक जोड़ें',
      'quantity_to_add': 'जोड़ने के लिए मात्रा',
      'current_stock': 'वर्तमान स्टॉक',
      'stock_qty_label': 'स्टॉक मात्रा',
      'critical_stock_alert': '📦 क्रिटिकल स्टॉक अलर्ट!',
      'order_now': 'अभी ऑर्डर करें',
      'remind_me': 'बाद में याद दिलाएं',
      'supplier_msg_template': 'नमस्ते! मुझे {product} की तत्काल डिलीवरी चाहिए। मेरा वर्तमान स्टॉक केवल {qty} है। कृपया जल्द भेजें। धन्यवाद! - {shop}',
      'self_reminder_template': '📌 रिमाइंडर: {product} और खरीदें। केवल {qty} बचे हैं।',
      'bill_generator': '🧾 बिल जेनरेटर',
      'customer_whatsapp': 'ग्राहक व्हाट्सएप नंबर',
      'tap_product_to_add': 'बिल में जोड़ने के लिए सामान पर टैप करें:',
      'bill_helper_text': 'बिल सीधे इस नंबर पर भेजा जाएगा',
      'add_items_first': 'पहले बिल में सामान जोड़ें!',
      'send_bill_whatsapp': 'व्हाट्सएप पर बिल भेजें',
      'total': 'कुल',
      'cash_in': '💰 नकद आय',
      'units_sold_label': '📦 बेची गई इकाइयां',
      'store_superstar': '🏆 स्टोर सुपरस्टार',
      'growth_trend': '📈 विकास दर (पिछले 7 दिन)',
      'all_performance': '🔥 सभी बिक्री प्रदर्शन',
      'sold_count_template': 'इस सप्ताह {count} बार बिका!',
      'thank_you_shopping': 'खरीदारी के लिए धन्यवाद!',
      'voice_sold': '{product} के {qty} यूनिट बिक गए।',
      'voice_added': '{product} में {qty} यूनिट जोड़े गए।',
      'voice_new_product': 'नया सामान {product} {qty} यूनिट के साथ जोड़ा गया।',
      'voice_stock_status': 'आपकी दुकान में {product} के {qty} यूनिट बचे हैं।',
      'voice_not_found': 'मुझे आपकी इन्वेंट्री में {product} नहीं मिला।',
      'voice_error': 'क्षमा करें, मुझे समझ नहीं आया।',
      'stock_low_warning': '{product} बहुत कम है: केवल {qty} बचे हैं!',
      'reorder_reminder_time': 'रिमाइंडर का समय',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'te', 'hi'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
